version: "3.5"
services:
  impgen:
    image: impgen:latest
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan/work
    networks:
      - impgen
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  impgen:
